export interface EssayBlock {
  type: "heading" | "paragraph";
  text: string;
}

export interface Essay {
  slug: string;
  title: string;
  subtitle: string | null;
  summary: string;
  date: string;
  note: string;
  body: EssayBlock[];
}

export const ESSAYS: Essay[] = [
  {
    slug: "it-rules-2021",
    title: "Is the Freedom of Expression Under Threat: The IT Rules, 2021 Explained",
    subtitle: null,
    summary: "On the IT Rules, 2021, and the real fight behind them: the Indian State versus Big Tech's claim to be a mere \"intermediary.\"",
    date: "2021",
    note: "Editor’s note: this was written five years ago and is open to discussion and change, but not conflict.",
    body: [
      { type: "paragraph", text: "The newly enacted the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 – or IT Rules, 2021, for short – have been criticised for infringing on people’s right to privacy and freedom of expression. Many people have expressed fear that the new provisions will be used by the government to silence their publicly expressed opinions and access their privately held conversations. These concerns are valid, given the abundance of routine misuse of power by political leaders to target people over dissent and criticism. Any claim of laws being used only for their stated objectives and not to hound political dissidents comes from a place of naivety and ignorance of India’s administrative and judicial landscape. People are charged under various laws; the investigative process and trial period in court ends up taking years; and the process becomes a form of punishment itself." },
      { type: "heading", text: "So, are any of the fundamental rights in danger?" },
      { type: "paragraph", text: "Ironically, it is the very misuse of laws to target genuine criticism that proves that the people need not fear any infringement of their rights of privacy and expression. The governments do not need new rules to go after common citizens and their political rivals; they have more than enough existing laws that fulfil this purpose. Moreover, they have all been upheld to be in alignment with the constitution by the Supreme Court as well." },
      { type: "paragraph", text: "Thus, the IT Rules, 2021 have no effect on the powers of government agencies to charge people and put them under trial – they have been doing this for decades. This dark albeit realist take on the rules is not to argue in favour of the rules; rather, it necessary if one truly wishes to understand the agenda behind them. The IT Rules 2021 deal less with the concerns of how to deal with public opinion than they do with the battle for power between the Indian State and the Big Tech." },
      { type: "heading", text: "How is it related to the Big Tech?" },
      { type: "paragraph", text: "The Big Tech refers to IT companies who enjoy a collective monopoly over the internet space. Companies such as Google, Twitter, Facebook (with WhatsApp and Instagram) control the digital space of social media almost between themselves. For long, tech companies, like Facebook and Twitter, have maintained that they are mere intermediary platforms. This position entails that the nature of the content on these platforms are the responsibility of the users and not of the companies themselves. They are a merely “service provider” and not a party to any exchange of information and data on the platform. Thus, they are not liable for any legal repercussions if a user violates any law of the land." },
      { type: "paragraph", text: "Yet, time and again this role has been overstepped by these billion-dollar giants. Google and Facebook have been reported to filter out which news gets preference based on the money they receive from the publishers. Twitter, recently, got into a conflict with the Indian authorities over its act of deeming tweets by political individuals with “Manipulated Media” tag. Both these incidents showcase an active role played by these platforms – that of becoming an Editor of the content on their platforms." },
      { type: "heading", text: "What role do the companies play?" },
      { type: "paragraph", text: "The issue in the conflicting positions by the Big Tech brings in the matter of legal accountability. In the case of Twitter, it made itself a party to both the national discourse as well as the police investigation which is expected to deem whether the charges made by a political party against another were true or fabricated. By doing so, it opened up a plethora of legal loopholes and ethical standpoints that are irrelevant to the credibility of the original allegations and counter-allegations made by political parties and common public alike. Some of the questions raised in the fiasco are:" },
      { type: "paragraph", text: "Whether an intermediary can edit or influence the content and other forms of expression as to how they will reach other users?" },
      { type: "paragraph", text: "If it can, is it comparable to judgements by the Indian courts and what if the court deems the opposite stand in its verdict?" },
      { type: "paragraph", text: "Since a newspaper or a fact-checker organisation is liable to be taken to court for the reports it publishes, where they must prove claims, what judicial oversight is present for the Big Tech?" },
      { type: "heading", text: "What is the primary objective of the new rules?" },
      { type: "paragraph", text: "So far, the Big Tech has evaded any scrutiny by offhandedly replying to any and all judicial questioning with this phrase: “Go to America. We are just a marketing enterprise”. In the absence of a legal framework, the Indian Legal System has been struggling with these questions much before the Twitter incident of May 2021. In the endeavour to resolve them, the IT Rules, 2021 were drafted and have been in force since 25th February 2021 as well. The rules define the role of the companies to what they claim – an intermediary platform. Further, if they choose to take on the role of editor at the same time, then they will be treated as editors. In such a scenario, the rules dictate that they will be subjected to the same laws as the users themselves. Thus, the legal immunity the Big Tech has proclaimed since the advent of digital era has now been replaced by legal framework of operations." },
      { type: "heading", text: "What about the common public and their rights?" },
      { type: "paragraph", text: "Article 19, which gives us the freedom of expression, and Article 21, which gives us the right to privacy, have always had restrictions within the constitutional ambit:" },
      { type: "paragraph", text: "“reasonable restrictions…in the interests of the sovereignty and integrity of India, the security of the State, friendly relations with foreign States, public order, decency or morality” and “No person shall be deprived of his life or personal liberty except according to procedure established by law”." },
      { type: "paragraph", text: "In other words, it is since 26 January 1950 that anyone can be charged on account of being in violation of these limits. Making or repealing of laws will continue to have no effect on the mental, emotional and psychological duress that one goes through due to a politically charged case. It is the excruciatingly slow judicial process in Indian courts that allows governments to harass people by turning the trial period into an inherent punishment." },
      { type: "heading", text: "Does this mean the common citizens must give up all rights?" },
      { type: "paragraph", text: "Unfortunately, one must accept that every law is and will be misused. Further, the power to deem any particular case as being politically charged or manipulated resides with the Indian courts; neither with a foreign company, nor with the common public. Advocating in the favour of constitutional authority must not be equated with condoning the frequent harassment of citizens by authorities. It is a reality that the governments weaponize legal frameworks which cannot be done away with in its entirety to go after their critics, instead of engaging them politically. Therefore, a new reality ought to be imagined and forged that balances the rights alongside the freedom and goes beyond the dichotomy of unjustified restrictions on the society and unchecked threat to society itself." },
      { type: "paragraph", text: "To its credit, the Supreme Court recently announced to take up the sedition law and define what constitutes as “the interests of the sovereignty and integrity of India, the security of the State”. Another welcome step will be to neutralise the aspect of the laws that allows for their misuse – by speeding up the investigative and the judicial process. Through this, the Judiciary organ of the State can effectively keep the Executive in check without compromising on the matter of national security and integrity." },
    ],
  },
  {
    slug: "afghanistan-2021",
    title: "Afghanistan: The Human Cost of Geostrategic Fanaticism",
    subtitle: null,
    summary: "On the human cost of the Taliban's 2021 advance, and the geostrategic calculus of the powers circling Afghanistan.",
    date: "August 2021",
    note: "Editor’s note: this was written five years ago and is open to discussion and change, but not conflict.",
    body: [
      { type: "paragraph", text: "On 8 May 2021 – as the global community polarized along the Israel-Hamas conflict – a bomb attack outside a school in the heart of Kabul killed over 90 people, majority of them young girls. All the victims belonged to one of the most persecuted minority communities in the region, the Hazaras." },
      { type: "paragraph", text: "For the international community, the number is useful in coming up with creative ways to further one’s strategic interests in the region. Pakistan, China, Iran and India share geographical borders as well as cultural and ethnic history. Other nations such as US, Russia, Turkey, France, UK, Germany have ideological and geopolitical interests within the nation." },
      { type: "heading", text: "Brief Historical Context:" },
      { type: "paragraph", text: "The conflict in Afghanistan goes back to the 19th century, when the region acted as a “buffer zone” between the Russian Empire and the British Indian Empire. As this rivalry evolved over the course of the 20th century, the Cold War era witnessed increased participation of additional foreign actors apart from UK and USSR: US, China, Iran, Turkey, Pakistan and India." },
      { type: "paragraph", text: "Across the border, the 1979 Iranian Revolution undid decades of western neo-imperialism to make way for an Islamic Republic, led by a religious leader, Ayatollah Khomeini. This development in the neighbourhood emboldened the local tribes in the hinterlands of Afghanistan to begin insurgent warfare against the Socialist Afghanistan Government." },
      { type: "paragraph", text: "From 1979 to 1989, the Soviet-Afghan War was fought by the US-backed Mujahideen groups and USSR-backed Afghan forces, which was soon followed by another decade of Civil War. However, the Taliban began an all-out war against their benefactors and captured Afghanistan. Since 2001, Afghanistan has been a site for US’s Global War on Terrorism." },
      { type: "heading", text: "What About The Afghan People?" },
      { type: "paragraph", text: "As the news of Reuters journalist Danish Siddique being killed in Afghanistan reached his homeland, the Indian community found its latent connection with the conflict. He was caught in the cross-firing between Taliban and ANDSF in the Spin Boldak district, which the Taliban captured within days of his death." },
      { type: "paragraph", text: "Soon horrifying reports poured in from Spin Boldak, as Taliban was reported to have killed over 100 civilians – after it had already captured the villages, a deviation from their usual strategy." },
      { type: "paragraph", text: "Ethnic minority groups, such as Hazaras, Uzbeks, and Tajiks – who make up the anti-Taliban forces – and religious minority communities of Hindus, Sikhs, Christians have been reporting mass slaughter, rape, looting and ethnic cleansing by the Pashtuni Taliban." },
      { type: "paragraph", text: "At present, UN estimates that 18.4 million people are in need of dire humanitarian assistance while over 5 million people have been internally displaced so far. According to a UNAMA report published in July, 1,659 civilians have been killed in the Afghanistan conflict during the period of January-June 2021 – one-third of whom were children." },
      { type: "paragraph", text: "Since then, the dead and the persecuted have been memorialized in the footnotes of the record books kept by global watch-bodies like the United Nations Assistance Mission in Afghanistan (UNAMA)." },
      { type: "heading", text: "What Are Other Countries Doing?" },
      { type: "paragraph", text: "With each passing day as Taliban forces advance towards Kabul, in the backdrop of US retreat, the prominent discourse within international community has focused on the strategic implications for different nations." },
      { type: "paragraph", text: "Turkey, a NATO and OIC member, is looking to gain control of the Kabul International Airport after US Army finalizes its retreat." },
      { type: "paragraph", text: "The Pakistani regime, on the other hand, is interested in the paradigmatic shift due to Taliban’s ideology – as it hopes to rejuvenate the insurgency movement in neighbouring Kashmir valley in India, like in 1980s and 1990s." },
      { type: "paragraph", text: "However, its contested international border of Durand Line, which is not recognized by the Taliban, threatens to put the country in a complex conflict with ethnic groups from both Pakistan and Afghanistan." },
      { type: "paragraph", text: "China’s treatment of Uyghur Muslims does not get recognised or opposed by most of the world, out of various economic and political considerations. Yet the ongoing genocide has found strong resistance from cross-border groups such as East Turkestan Islamic Movement (ETIM), which is said to have bases in Afghanistan." },
      { type: "paragraph", text: "In the latest meetings between Taliban and Chinese delegates, China asserted that the former actor can hope for China’s aid in rehabilitation process only if it cracks down on ETIM. Despite being a self-advocate for salvation of Muslims from global oppression, Taliban’s official stance on Uyghurs reflects China’s agenda." },
      { type: "paragraph", text: "India’s position, as stated by the External Affairs Ministry, is of engaging in discussions with “all stakeholders” and a complete rejection of violent overthrow of government. Over the course of last few years, there have been reports of backchannel meetings between Indian and Taliban delegates – signifying an evolving dynamic with the rapidly changing ground reality." },
      { type: "paragraph", text: "The United Nations High Commissioner for Human Rights, Michelle Bachelet, meanwhile, has strongly condemned the “deeply disturbing reports” while the UN Secretary-General, Antonio Guterres, stated on 12 August 2021 that he is “following escalation in fighting with deep concern”." },
    ],
  },
  {
    slug: "ukraine-biden-2021",
    title: "Biden Just Did What Trump Was Impeached For – Stop Military Aid to Ukraine",
    subtitle: "Biden executed his powers as the President of the United States in negotiating with the aggressor against their ally. Biden did what Trump tried to do, both with their prerogatives which they hoped to aid them elsewhere.",
    summary: "On Biden freezing military aid to Ukraine days after meeting Putin in Geneva — and why it echoes what got Trump impeached.",
    date: "June 2021",
    note: "Editor’s note: this was written five years ago and is open to discussion and change, but not conflict.",
    body: [
      { type: "heading", text: "Geneva Summit" },
      { type: "paragraph", text: "On June 16, the city of Geneva witnessed the first meeting of the two most powerful leaders in the world – Joe Biden, President of the United States, and Vladimir Putin, President of the Russian Federation. In the past, both the leaders have been at odds with each other, to the extent of calling the other person a “killer”. The importance of this meet, therefore, can hardly be understated given the history of hostility at a personal level as well as an emerging neo-Cold War between US and Sino-Russian alliance." },
      { type: "paragraph", text: "The two leaders rallied the media and the public behind them to boost their respective images at home and project their national interests on the global stage. In a faux pas, President Biden referred to President Putin as “President Trump”. Whether this act was intentional and symbolic, or a slip up given the theories around Joe Biden’s dementia, is open to debate." },
      { type: "heading", text: "US, Ukraine, Russia" },
      { type: "paragraph", text: "Notably, an interesting yet ironic development has unleashed comparisons with Donald Trump – not with Putin, but Biden. Two days after the Geneva summit, Politico reported (link) that the Biden Administration has frozen military aid to Ukraine worth 100 million dollars. The aid was approved to respond to the recent stationing over 100,000 Russian soldiers along its border with Ukraine." },
      { type: "paragraph", text: "According to the White House press release on the issue, the reports of stopping any military aid are “nonsense”. The official statement attempts to contradict the claim, without contradicting it, and makes a reference to a 150-million-dollar package to Ukraine. This package, however, is separate from the military aid in question." },
      { type: "paragraph", text: "The same release mentions the freezing of US aid in a trivial manner: “We have also prepared contingency funds in the event of a further Russian incursion into Ukraine”. In other words, the aid is now “contingency funds” which come with the condition of Russian incursion." },
      { type: "paragraph", text: "In the backdrop of the Geneva meeting and the freezing of aid to Ukraine, one question is inevitable – Isn’t this what Trump tried to do and was impeached for?" },
      { type: "heading", text: "Why is Ukraine in the picture?" },
      { type: "paragraph", text: "In 2014, Russia sent their armed forces to Crimea in Ukraine and annexed the region. Later, they held a “referendum”, with tanks and soldiers abound the booths, which failed to receive any international recognition. During the conflict, the then Vice-President Biden handled the US support to Ukraine against Russian aggression. Around the same time, his son, Hunter Biden, joined a Ukrainian gas company, Burisma Holdings, which also had a natural gas extraction operation in the Crimean Peninsula." },
      { type: "paragraph", text: "Multiple reports of corruption, conflict of interests, illegitimate deals and abuse of office had already begun surfacing in 2014. Yet, given the threat Ukraine faced along her borders, having already lost significant territory to a foreign power, the matter of Hunter Biden was never brought to legal scrutiny under any Ukrainian law." },
      { type: "heading", text: "What transpired between Trump and Zelensky regarding Biden?" },
      { type: "paragraph", text: "In 2019, media reports pointed towards a whistle-blower who got hold of conversations between Trump officials and Ukrainian government of Volodymyr Zelensky – a comedian/actor turned President. It was reported that President Trump was attempting to condition Congress-approved US aid to Ukraine in return for legal investigations for corruption into the Bidens – Joe Biden and his son, Hunter Biden." },
      { type: "paragraph", text: "Through the transcripts of official and unofficial meetings and discussions, it became clear that Trump’s objective was to “unearth” the alleged corruption from 2014 via legal investigations in Ukraine and use the political dirt against his 2020 Presidential Election rival, Joe Biden. In essence, he tried to leverage foreign policy affair for domestic politics arithmetic – a banal and routine modus operandi in international relations and global diplomacy." },
      { type: "heading", text: "How did it culminate into Trump’s first impeachment?" },
      { type: "paragraph", text: "Nevertheless, the Democratic party saw the allegations of quid-pro-quo diplomacy of President Trump as being in violation of the oath of the office and initiated the first of the two impeachment proceedings against him on 24 September 2019. Unsurprisingly, the Democrat-majority House impeached him on 18 December while the Senate acquitted him on February 5, 2020, in absence of the mandatory two-third majority which neither the Democrats nor the Republicans enjoyed." },
      { type: "paragraph", text: "While the outcome of the impeachment inquiry and trial was predictable, the process threw open many questions. Among the most burning ones was the timing of the trial against “abuse of the office of the President”. The Democratic Party did not implore the path of impeachment throughout the tenure of Trump Administration despite unceasingly declaring his policies to be in violation of the Office Oath and the Constitution." },
      { type: "paragraph", text: "Yet, they rushed for impeachment when the target of Trump’s politics was opening an investigation into corruption and abuse of power by the Bidens – something that the information in public domain alludes to. While the nature of the allegations of corruption by Trump for political gain cannot be discarded, the entire episode has gained relevance once again with the developments this week." },
      { type: "heading", text: "Did Biden do what Trump attempted and got impeached for?" },
      { type: "paragraph", text: "Conditioning aid to Ukraine on actions by other entities is what got Trump impeached by the strength of numbers in the House of Representatives, with allegations against him of helping their “enemy” Russia and leaving an ally defenceless. The Biden Administration’s decision to freeze the funds to Ukraine only two days after the Geneva meet between Biden and Putin follows a normal framework of foreign policy." },
      { type: "paragraph", text: "In addition, it also follows the precedent of brokering international deals through demonstration of power or trade of goods and services. President Trump’s attempt to condition military aid to a foreign power fell within the purview of his powers via the White House in the same manner as President Biden’s decision to withhold military aid and make it conditional to Ukraine and Russia’s situation." },
      { type: "heading", text: "Were any rules broken by Biden and Trump in dealing with Ukraine?" },
      { type: "paragraph", text: "Biden executed his powers as the President of the United States in negotiating with the aggressor against their ally. Biden did what Trump tried to do, both with their prerogatives which they hoped to aid them elsewhere. One cannot negotiate internationally without power at home; one cannot enjoy power if they fail to negotiate abroad. In order to get something, you have to concede something in exchange. Diplomacy is simply an exercise in sales & marketing, just on a bigger and more global scale. In this case, the table has nuclear-armed nations at its either end." },
    ],
  },
];
